name: shared
description: Package whith helpers (extensions etc.).
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fleasy: ^0.13.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  deep_pick: ^0.10.0
  ntp: ^2.0.0
  http: ^0.13.4