name: monopoly_banking
description: Unofficial banking companion app for monopoly board games
publish_to: "none"

version: 0.8.3+14

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fleasy: ^0.13.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  kt_dart: ^1.0.0
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.3.0
  currency_text_input_formatter: ^2.1.8
  modal_bottom_sheet: ^3.0.0-pre
  confetti: ^0.7.0
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7
  share_plus: ^7.0.1
  cached_network_image: ^3.2.3
  routemaster: ^1.0.1
  qr_flutter: ^4.0.0
  firebase_core: ^2.4.0

  user_repository:
    path: packages/user_repository
  banking_repository:
    path: packages/banking_repository

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google_logo.png

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#303030"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
