name: monopoly_banking
description: A cloud-based monopoly mobile banking app.
publish_to: 'none'

version: 0.8.1+12

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fleasy: ^0.13.0
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.3
  kt_dart: ^0.10.0
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.1.0
  currency_text_input_formatter: ^2.1.5
  modal_bottom_sheet: ^2.0.1
  confetti: ^0.6.0
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.0
  share_plus: ^4.0.4
  cached_network_image: ^3.2.0
  routemaster: ^1.0.0
  qr_flutter: ^4.0.0

  user_repository:
    path: packages/user_repository
  banking_repository:
    path: packages/banking_repository


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google_logo.png

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#303030"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
