name: user_repository
description: Package which manages the authentication and user data.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.3.0
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  google_sign_in: ^5.4.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  fleasy: ^0.13.0
  deep_pick: ^0.10.0
  kt_dart: ^1.0.0

  shared:
    path: ../shared
