name: Build & deploy to Firebase Hosting (staging) on new release.

on:
  release:
    types: [published]
  workflow_dispatch:  # This line allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: 3.7.12
      - run: flutter pub get
      - run: flutter build web -t lib/main_staging.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONOPOLY_BANKING_STAGING }}'
          channelId: live
          projectId: monopoly-banking-staging
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
